### ISSUE TITLE
Request for OSC hooks for named layers

### ISSUE THREAD

**Issue by smukkejohan** [anome/millumin-dev-kit#1]
I am really missing a way to control layers by name rather by the index. Its a big hassle to update all of my faders every time I add in a new layer to a board.

I often work with millumin as a tool for compositing different masks and syphon inputs together from other software, then sometimes I would like to change the layer order for the compositing live, without breaking all my faders for those layers. 

I would like to be able to do e.g. /millumin/layer/opacity/[LAYERNAME] 75

**Comment by anome** [comment]
Hello @mrbichel,

As now, we didn't plan to add such a feature, but feel free to submit an idea on Uservoice : http://millumin.uservoice.com
It helps us to keep track of user requests, and see their popularity. Thank you.

Best. Philippe

**Comment by reno-** [comment]
Hi,
Controlling the layers with the index name could be more intuitive because your interface shows the layer's order.
One trick to be more confortable with a touchOsc or a lemur interface is to put a label next to the fader and listen the name of the layer.
I'm not sure millumin already sends the name of the layer when you send a ping, but I guess yes.
And if it doesn't, it sounds like a tiny feature to implement?
;-)

Best regards,

Renaud

**Comment by PhilipHamilton** [comment]
Layers are backwards in Millumin's implementation of OSC. Top down is how it should be. Then accessing a layer by name would less important.

Still when changing layer orders it would be a very useful feature to get working I agree with mrbichel

**Comment by anome** [comment]
Closed : present in the OSC API for Millumin V2.
See [here](https://github.com/anome/millumin-dev-kit/wiki/OSC-documentation) for more info.
